name = "orange-meets"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"
account_id = "16f4ff399775a540116f556fa200699a"
main = "./build/index.js"

[site]
  bucket = "./public"

 [[rules]]
      type = "ESModule"
      globs = [ "**/*.js" ]

[vars]
CALLS_APP_ID="a6c7a1ac431aa001f1498982a133855a"
CALLS_APP_SECRET="aee50524c0b90d9c70e76de8024d80c0095fa4b0bbf4a5a28acb9c2e45b72674"

[durable_objects]
 bindings = [
  { name = "rooms", class_name = "ChatRoom" }
]

# Indicate that you want the ChatRoom class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]

# The necessary secrets are:
# - CALLS_APP_SECRET
# To add secret, run `echo <VALUE> | wrangler secret put <NAME>`
